Fix helper service version reporting

diff --git a/assets/alpine/myst-service b/assets/alpine/myst-service
--- a/assets/alpine/myst-service
+++ b/assets/alpine/myst-service
@@ -1,13 +1,8 @@
 #!/sbin/openrc-run
 
-while true
-do
-    if [ -f /.env.myst ]; then
-      break
-    fi
-    sleep 5
-done
-source /.env.myst
+if [ -f /.env.myst ]; then
+  source /.env.myst
+fi
 
 name="Mysterium Network Node"
 command="myst"
@@ -16,19 +11,21 @@ command_background=true
 pidfile="/run/${RC_SVCNAME}.pid"
 
 depend() {
-        need net
+  need net
 }
 
 start_pre() {
-    while true
-    do
-        l=`find /root/.mysterium/keystore -type f | wc -l`
-        if [ $l -ge 2 ]
-        then
-          logger Keystore found..
-          break
-        fi
-        echo Waiting for keystore..
-        sleep 5
-    done
+  if ! [ -f /.env.myst ]; then
+    echo "Error: /.env.myst is absent" 
+    exit 1
+  fi
+
+  l=`find /root/.mysterium/keystore -type f 2>/dev/null | wc -l`
+  if [ $l -ge 2 ]
+  then
+    logger Keystore found..
+  else
+    echo "Error: keystore not found" 
+    exit 1
+  fi
 }
